import type { Locale } from './copy';
import type { LessonId } from './core/training';

interface LevelCopy { title: string; description: string; tip: string; threat: string }
interface LessonCopy { title: string; action: string; watch: string; success: string }
export const campaignCopy = {
  sk: {
    title: 'Od prvého podu po piatkový incident.', eyebrow: 'ON-CALL AKADÉMIA', menu: 'Levely',
    intro: 'Nauč sa služby v tréningu. Potom udrž produkciu nažive v štyroch čoraz náročnejších smenách.',
    tutorial: 'Tréning', startTutorial: 'Spustiť tréning', replay: 'Zopakovať tréning', select: 'Spustiť level',
    completed: 'Splnené', locked: 'Najprv dokonči level', available: 'Pripravené', waves: 'vlny',
    lesson: 'Lekcia', next: 'Ďalšia lekcia', retry: 'Zopakovať ukážku', exit: 'Späť na levely',
    selectTile: 'Vybrať zvýraznenú dlaždicu', selectPod: 'Vybrať pod na mape',
    buildHint: 'Klikni na zvýraznenú dlaždicu, potom na odporúčanú službu. Ostatné ovládanie si vyskúšaš v ďalších lekciách.',
    trainingTag: 'TRÉNINGOVÝ CLUSTER', trainingHint: 'Každá lekcia má vlastný rozpočet a pripravený traffic. Do rekordov sa nezapočítava.',
    action: 'Tvoj krok', watch: 'Sleduj službu', done: 'Hotovo — takto to funguje',
    finish: 'Dokončiť tréning a začať level 01', progress: 'služby → vylepšenie → on-call schopnosti',
    levelWon: 'Smena zvládnutá.', levelWonCopy: 'Produkcia prežila. Ďalší level je odomknutý a pridá novú hrozbu.',
    finalWonCopy: 'Zvládla si celú kampaň. Teraz môžeš skúsiť nekonečnú smenu.', nextLevel: 'Ďalší level',
    again: 'Zopakovať level', newSeed: 'Nový seed', duration: 'min', practiceDuration: '3–5 min · vlastným tempom',
    trainingComplete: 'Všetky služby aj schopnosti máš odskúšané. V prvej smene ich už spojíš do vlastnej obrany.',
    briefing: 'Úloha', victory: 'Preži všetky vlny so SLO nad 0 a kladným rozpočtom.',
    startWave: 'Spustiť prvú vlnu', backToGame: 'Späť do hry',
    levels: [
      { title: 'Prvý deň na on-calle', description: 'Šesť služieb, vylepšenie a štyri schopnosti. Postav, vyskúšaj, pochop.', threat: 'Bez časového tlaku', tip: 'Hra počká na tvoj krok. V každej lekcii máš čistý cluster a nový rozpočet.' },
      { title: 'Pokojná smena', description: 'Bežní používatelia a prvý newsletter. Nauč sa vyvážiť spracovanie a náklady.', threat: 'GET + POST', tip: 'API Pod na dlaždici 3, 3 a Valkey na 5, 3 sú dobrý začiatok. Queue na 7, 3 zachytí POSTy. Nechaj si aspoň 40 € na prevádzku.' },
      { title: 'Sme na Hacker News', description: 'Zrazu prichádzajú boti. Cache už sama nestačí a traffic sa zahusťuje.', threat: '+ Bot roj', tip: 'Rate limiter patrí blízko vstupu. Za ním nechaj pod a cache pre bežných používateľov. S vlnami pridávaj kapacitu.' },
      { title: 'Payload too large', description: 'Ťažké uploady blokujú requesty, pody sa zasekávajú a DB migruje.', threat: '+ Veľké uploady + migrácia', tip: 'Vylepšuj pody na viac replík a stráž červené označenie zaseknutia. Reštart [1] vypne pod na 3 sekundy; hodí sa záložná kapacita.' },
      { title: 'Deploy Friday', description: 'Kolega mergol a odišiel. Sedem vĺn až do polnoci, vrátane retry stormov.', threat: '+ Retry storm', tip: 'Retry po 18 sekundách na timeoute vytvorí tri ďalšie requesty. Rozkladaj záťaž, škáluj s rozumom a odlož si rollback na katastrofu.' },
    ] satisfies LevelCopy[],
  },
  en: {
    title: 'From your first pod to Friday’s incident.', eyebrow: 'ON-CALL ACADEMY', menu: 'Levels',
    intro: 'Learn the services in training. Then keep production alive through four increasingly demanding shifts.',
    tutorial: 'Training', startTutorial: 'Start training', replay: 'Replay training', select: 'Start level',
    completed: 'Completed', locked: 'First complete level', available: 'Ready', waves: 'waves',
    lesson: 'Lesson', next: 'Next lesson', retry: 'Retry demonstration', exit: 'Back to levels',
    selectTile: 'Select the highlighted tile', selectPod: 'Select the pod on the map',
    buildHint: 'Click the highlighted tile, then the recommended service. You will try the other controls in later lessons.',
    trainingTag: 'TRAINING CLUSTER', trainingHint: 'Each lesson has a fresh budget and prepared traffic. Training never enters the leaderboard.',
    action: 'Your turn', watch: 'Watch the service', done: 'Done — here is why it worked',
    finish: 'Finish training and start level 01', progress: 'services → upgrades → on-call abilities',
    levelWon: 'Shift complete.', levelWonCopy: 'Production survived. The next level is unlocked and introduces a new threat.',
    finalWonCopy: 'You survived the entire campaign. The endless shift is now unlocked.', nextLevel: 'Next level',
    again: 'Replay level', newSeed: 'New seed', duration: 'min', practiceDuration: '3–5 min · at your pace',
    trainingComplete: 'You have tried every service and ability. In the first shift, combine them into your own defense.',
    briefing: 'Your mission', victory: 'Survive every wave with SLO above zero and money left in the budget.',
    startWave: 'Start the first wave', backToGame: 'Back to game',
    levels: [
      { title: 'Your first on-call shift', description: 'Six services, an upgrade and four abilities. Build it, try it, understand it.', threat: 'No time pressure', tip: 'The game waits for your action. Every lesson starts with a fresh cluster and budget.' },
      { title: 'A quiet shift', description: 'Regular users and the first newsletter. Balance processing capacity with running costs.', threat: 'GET + POST', tip: 'An API Pod at tile 3, 3 and Valkey at 5, 3 are a good start. Queue at 7, 3 catches POSTs. Keep at least €40 for upkeep.' },
      { title: 'We are on Hacker News', description: 'Now the bots arrive. Cache alone will not save you, and traffic is getting thicker.', threat: '+ Bot swarm', tip: 'Put a rate limiter near ingress. Keep a pod and cache behind it for real users. Add capacity as waves grow.' },
      { title: 'Payload too large', description: 'Heavy uploads block requests, pods jam, and the database is migrating.', threat: '+ Big uploads + migration', tip: 'Upgrade pods for more replicas and watch for red jam labels. Restart [1] takes a pod offline for 3 seconds; keep spare capacity nearby.' },
      { title: 'Deploy Friday', description: 'Your colleague merged and left. Seven waves until midnight, retry storms included.', threat: '+ Retry storm', tip: 'A retry timing out after 18 seconds returns as three requests. Spread the load, scale carefully, and save rollback for a catastrophe.' },
    ] satisfies LevelCopy[],
  },
};
export const lessonCopy: Record<Locale, Record<LessonId, LessonCopy>> = {
  sk: {
    pod: { title: 'Pod: tvoja prvá obrana', action: 'Zelené GET requesty idú z INGRESS k DB. Nespracované uberajú SLO — tvoje životy. Postav API Pod za 45 € na zvýraznenej dlaždici vedľa cesty.', watch: 'Pod spracúva jeden request naraz v kruhu svojho dosahu. Sleduj lúč, počítadlo spracovaných a príjem do rozpočtu.', success: 'Tri GETy vybavené. Pod zarába spracovaním, no jeho prevádzka stojí 0,12 €/s. Prázdny rozpočet ukončí smenu rovnako ako nulové SLO.' },
    cache: { title: 'Valkey: rovnaká práca iba raz', action: 'Postav Valkey na označené miesto. Pošleme štyri GETy rovnakej farby, teda s rovnakým cache kľúčom.', watch: 'Prvý GET naučí cache farbu. Ďalšie zásahy zmiznú ihneď. Kľúč zostáva uložený iba do vypršania TTL.', success: 'Štyri GETy vybavené za zlomok času podu. Cache však ignoruje POSTy aj botov. Vylepšenie predĺži TTL a zrýchli vyhľadávanie.' },
    queue: { title: 'Queue: POSTy nemusia panikáriť', action: 'Postav Queue. Modré POSTy majú viac práce na spracovanie. Fronta ich dokáže bezpečne podržať.', watch: 'Tri POSTy sa zastavia v buffri. Jeden consumer ich postupne vybavuje a počas čakania vo fronte nemajú timeout.', success: 'Všetky tri POSTy sú vybavené. Queue vylepšením získa ďalšieho consumera aj viac miest. GETy, botov a uploady fronta nezachytí.' },
    limiter: { title: 'Rate limiter: odfiltruj roj', action: 'Tentoraz príde deväť oranžových botov. Postav Rate limiter pri vstupe. Valkey by ich nezastavila.', watch: 'Limiter spomaľuje botov vo svojom dosahu a spracúva ich po skupinách. Sleduj, ako sa roj zmenšuje.', success: 'Roj zastavený. Vylepšenie obmedzí aj ostatný traffic a zvýši počet botov, ktoré limiter naraz zahadzuje.' },
    balancer: { title: 'Load balancer: rozdeľ prácu', action: 'Dva pody už čakajú na opačných stranách mapy. Postav Load balancer na zvýraznenej dlaždici, aby sa k nim traffic dostal.', watch: 'Requesty sa rozdelia cez dva modré uzly. Balancer sám nespracúva — predĺži a rozdelí cestu k pripraveným podom.', success: 'Obe vetvy dostali prácu. Balancer po vylepšení uprednostní menej vyťaženú vetvu. Používaj ho spolu so službami pozdĺž oboch ciest.' },
    autoscaler: { title: 'Autoscaler: kapacita nie je zadarmo', action: 'Jeden pod je pripravený. Postav vedľa neho Autoscaler. Pošleme špičku desiatich POSTov.', watch: 'Pri piatich blízkych requestoch začne scale-up. Po 3 sekundách dostane pod dočasnú repliku. Sleduj dva lúče a nárast nákladov.', success: 'Pod spracúva viac cieľov naraz. Aktívny Autoscaler pridáva k bežnej prevádzke 0,70 €/s za úroveň. Keď špička odíde, kapacita aj extra náklady klesnú.' },
    upgrade: { title: 'Upgrade: dve ruky namiesto jednej', action: 'Klikni na pripravený pod a v detaile stlač Vylepšiť. Za rozšírenie zaplatíš z rozpočtu.', watch: 'Pod na úrovni 2 už má dve repliky: môže spracúvať dva POSTy súčasne. Prevádzka je o niečo drahšia.', success: 'Vylepšenie funguje. Každá služba má najviac 3 úrovne. Tlačidlo Predať vráti 65 % celkovej investície, keď ju už nepotrebuješ.' },
    restart: { title: '1 · Have you tried restarting it?', action: 'Pod sme v tréningu zasekli. Červený nápis znamená, že nespracúva. Vyber pod a použi Reštart podu alebo kláves 1.', watch: 'Zaseknutie zmizlo, ale pod je 3 sekundy mimo. Po reštarte začne spracúvať GETy. Ďalší reštart bude dostupný po cooldowne.', success: 'Pod je späť. V ostrej hre ho môže zaseknúť dlhé spracovanie uploadov. Jeden reštart nezachráni všetky pody naraz.' },
    hotfix: { title: '3 · Rýchla oprava, pomalé následky', action: 'Skús Hotfix tlačidlom alebo klávesom 3. Na 10 sekúnd zdvojnásobí rýchlosť spracovania služieb.', watch: 'Najprv 2× rýchlosť. Potom sa objaví TECH DEBT: nasledujúcich 5 sekúnd služby spracúvajú iba polovičnou rýchlosťou.', success: 'Oprava aj tech debt prešli. Hotfix použi na špičku, ale počítaj s pomalým dobehom. Nový bude dostupný až po 45 sekundách.' },
    rollback: { title: '2 · Desať sekúnd druhej šance', action: 'Simulovaný incident práve zrazil SLO na 25 %. Použi Rollback alebo kláves 2 a vráť cluster o 10 sekúnd späť.', watch: 'Obnovuje sa skutočná história simulácie.', success: 'SLO je späť na 100 %. Obnovili sa aj requesty, služby a rozpočet. Rollback môžeš použiť iba raz za level — aj po prehre.' },
    mute: { title: '4 · Ticho nie je oprava', action: 'Nakoniec stlač Stíšiť alert alebo kláves 4. Slack prestane na 15 sekúnd pípať.', watch: 'Notifikácie sú stíšené.', success: 'Kľud na Slacku, rovnaké problémy v produkcii. Mute nemení spracovanie, SLO ani rozpočet. Teraz poznáš celú on-call výbavu.' },
  },
  en: {
    pod: { title: 'Pod: your first line of defense', action: 'Green GET requests travel from INGRESS to DB. Unprocessed requests reduce SLO — your health. Build an API Pod for €45 on the highlighted tile beside the path.', watch: 'A pod processes one request at a time within its range circle. Watch the beam, processed counter and income.', success: 'Three GETs handled. Processing earns money, but the pod costs €0.12/s to run. An empty budget ends the shift, just like zero SLO.' },
    cache: { title: 'Valkey: do the same work once', action: 'Build Valkey on the marked tile. We will send four GETs of the same color: the same cache key.', watch: 'The first GET teaches the cache its color. Cache hits disappear immediately. The key only stays stored until its TTL expires.', success: 'Four GETs handled much faster than a pod. Cache ignores POSTs and bots. Upgrades increase TTL and lookup speed.' },
    queue: { title: 'Queue: POSTs can wait safely', action: 'Build a Queue. Blue POSTs take more work to process. A queue can hold them safely.', watch: 'Three POSTs stop in the buffer. One consumer processes them in order, and queued requests cannot time out while waiting.', success: 'All three POSTs handled. Upgrades add a consumer and buffer slots. Queues do not catch GETs, bots or uploads.' },
    limiter: { title: 'Rate limiter: filter the swarm', action: 'Nine orange bots are coming. Build a Rate limiter near ingress. Valkey would not stop them.', watch: 'The limiter slows bots in range and drops them in groups. Watch the swarm shrink.', success: 'Swarm stopped. Upgrades slow other traffic too and increase the number of bots dropped simultaneously.' },
    balancer: { title: 'Load balancer: share the work', action: 'Two pods are already waiting on opposite sides of the map. Build a Load balancer on the marked tile to route traffic toward them.', watch: 'Requests split through the two blue junctions. A balancer does not process requests itself; it spreads and extends the path to the waiting pods.', success: 'Both branches received work. Upgraded routing prefers the less crowded branch. Pair the balancer with services along both paths.' },
    autoscaler: { title: 'Autoscaler: capacity has a price', action: 'One pod is ready. Build an Autoscaler nearby. We will send a spike of ten POSTs.', watch: 'Five nearby requests trigger scale-up. After 3 seconds the pod gets a temporary replica. Watch for two beams and rising running costs.', success: 'The pod now processes multiple targets. An active Autoscaler adds €0.70/s per level to its normal upkeep. Extra capacity and cost drop after the spike.' },
    upgrade: { title: 'Upgrade: two hands instead of one', action: 'Select the prepared pod and press Upgrade in its details. The extra capacity is paid from your budget.', watch: 'A level 2 pod has two replicas: it can process two POSTs at once. Its upkeep is slightly higher.', success: 'Upgrade complete. Each service has at most 3 levels. Sell refunds 65% of the total investment when you no longer need it.' },
    restart: { title: '1 · Have you tried restarting it?', action: 'We have jammed a pod for training. Its red label means it cannot process traffic. Select it and use Restart pod or key 1.', watch: 'The jam is cleared, but the pod is offline for 3 seconds. It then resumes processing GETs. Another restart requires the cooldown to finish.', success: 'The pod is back. Sustained upload processing can jam pods in real shifts. One restart cannot fix every pod at once.' },
    hotfix: { title: '3 · Fast fix, slow consequences', action: 'Try Hotfix with its button or key 3. It doubles service processing speed for 10 seconds.', watch: 'First, 2× processing. Then TECH DEBT appears: services process at half speed for the next 5 seconds.', success: 'The fix and debt are over. Use Hotfix for spikes but plan for the slower aftermath. Its cooldown is 45 seconds.' },
    rollback: { title: '2 · Ten seconds of second chances', action: 'A simulated incident just dropped SLO to 25%. Use Rollback or key 2 to restore the cluster from 10 seconds ago.', watch: 'Restoring actual simulation history.', success: 'SLO is back at 100%. Requests, services and budget were restored too. Rollback works only once per level, including after losing.' },
    mute: { title: '4 · Silence is not a fix', action: 'Finally, press Mute alert or key 4. Slack will stop pinging for 15 seconds.', watch: 'Notifications are muted.', success: 'A quiet Slack, the same production problems. Mute does not change processing, SLO or budget. You now know the whole on-call toolkit.' },
  },
};
