export type Locale = 'en' | 'sk';
export const copy = {
  en: {
    back: 'All games', eyebrow: '06 / TOWER DEFENSE · ON-CALL', tagline: "it's 16:55. someone just merged.",
    intro: 'Your colleague merged a PR and went home. Keep production alive until midnight. You are the entire on-call team.',
    live: 'PRODUCTION', ready: 'READY TO DEPLOY', paused: 'PAUSED', wave: 'Wave', budget: 'Cloud budget', burn: 'burn rate',
    runway: 'runway without income', slo: 'SLO remaining', served: 'processed', incoming: 'in flight',
    services: 'Service catalog', servicesHint: 'Select a tile, then deploy a service.', select: 'Select a tile on the cluster',
    tile: 'Tile', level: 'Level', upgrade: 'Upgrade', sell: 'Sell', max: 'Fully upgraded', deployed: 'Deployed services',
    start: 'Start the Friday', pause: 'Pause', resume: 'Resume', speed: 'Game speed', sound: 'Sound', help: 'Runbook',
    planning: 'Build your first line of defense.', planningHint: 'Start with an API Pod and Valkey beside the lit path. Nothing costs upkeep until you start.',
    cluster: 'eu-central-1 / friday-cluster', clusterHint: 'Click a tile to build · click a service to manage',
    keyboard: 'Arrow keys select a tile · Enter opens the build menu · Escape closes it',
    abilities: 'ON-CALL TOOLKIT', restart: 'Restart pod', rollback: 'Rollback', hotfix: 'Hotfix', mute: 'Mute alert',
    restartHint: 'Selected or jammed API pod: clear the jam, then 3 s offline. 18 s cooldown.',
    rollbackHint: 'Restore the cluster and budget from 10 seconds ago. Once per Friday, including after an incident.',
    hotfixHint: '2× processing for 10 s, then 5 s at half speed. 45 s cooldown.',
    muteHint: 'Silence Slack for 15 s. Production remains just as broken. 20 s cooldown.',
    used: 'used', readyAbility: 'ready', monitoring: 'OBSERVABILITY', latency: 'Processing latency', errors: 'Error rate', throughput: 'Throughput',
    latencyHint: 'Mean time from arrival to processing in the last second.', errorsHint: 'Leaks and timeouts / all completed requests in the last second.',
    slack: '#prod-on-fire', online: '1 online', muted: 'Notifications muted. Problems unchanged.',
    deploy: 'alex · 16:55', deployText: 'merged a tiny fix. heading out ✌️',
    newsletter: 'Marketing sent a newsletter.', hn: 'Someone posted us on Hacker News.', migration: 'DB migration running. Last hop slowed for 20 s.',
    welcome: 'You have €190. Maybe read the runbook.', reserved: 'Ingress, DB and routing junctions must stay clear.',
    occupied: 'That tile is occupied by a service or a request.', funds: 'Insufficient cloud budget.', blocked: 'Keep a route open from ingress and both junctions to DB.',
    built: 'Service deployed. What could go wrong?', upgraded: 'Upgrade shipped. No meeting required.', sold: 'Service removed. 65% refunded.',
    selectPod: 'Select an API Pod to restart.', jammed: 'An upload jammed a pod. Select it and restart [1].', rollbackWait: 'Rollback needs 10 seconds of history.',
    restartMessage: 'Have you tried turning it off and on?', rollbackMessage: 'The last 10 seconds never happened.', hotfixMessage: 'Ship it. Future you can pay the tech debt.', muteMessage: 'This is fine. 🔕',
    incident: 'Production has left the chat.', bankrupt: 'Your cloud card was declined.', survived: 'It’s midnight. You can log off.',
    lostCopy: 'The incident report can wait. Your next Friday starts with the same seed.',
    wonCopy: 'Seven waves. One engineer. Production is still standing. Endless mode is now unlocked.',
    again: 'Try this Friday again', newSeed: 'New Friday', endless: 'Endless shift', endlessLocked: 'Survive Friday to unlock endless',
    leaderboard: 'Local shift records', noRecords: 'Your first shift is still ahead of you.', seed: 'Seed', close: 'Close',
    runbookTitle: 'A very unofficial runbook',
    rules: [
      'Defend the DB for seven 75-second waves (about 9 minutes). Unprocessed requests reduce SLO. Zero SLO or an empty budget ends the shift.',
      'Click an empty tile and choose a service. Services block tiles, but the game never lets you seal the route. Click a service to upgrade it (up to level 3) or sell it for 65%.',
      'Start with an API Pod and Valkey near the lit route. Build during waves too. Processed requests earn €; every service has an upkeep cost. Watch your burn rate.',
      'GET is fast; POST needs a queue. Bots ignore cache. Big uploads slow traffic and can jam pods. A retry that times out after 18 s returns as three requests, up to two generations.',
      'Load balancers send requests through the two blue routing junctions. Upgrades prefer the less crowded branch. Autoscalers add temporary nearby pod capacity when five requests gather; scaling costs extra.',
      'Keys 1–4 activate abilities. Restart a selected or jammed pod. Rollback works once, even after losing. Space pauses. The shift also pauses when you leave this tab.',
    ],
    hot: 'HOTFIX · 2× processing', debt: 'TECH DEBT · ½ processing', jam: 'JAMMED', offline: 'RESTARTING', scaling: 'SCALING',
    unavailable: 'The cluster needs WebGL. Enable hardware acceleration and reload to play.', reload: 'Reload game',
  },
  sk: {
    back: 'Všetky hry', eyebrow: '06 / TOWER DEFENSE · ON-CALL', tagline: "it's 16:55. someone just merged.",
    intro: 'Kolega mergol PR a šiel domov. Udrž produkciu nažive do polnoci. Celý on-call tím si ty.',
    live: 'PRODUKCIA', ready: 'PRIPRAVENÉ NA DEPLOY', paused: 'PAUZA', wave: 'Vlna', budget: 'Cloud budget', burn: 'náklady',
    runway: 'výdrž bez príjmu', slo: 'Zostávajúce SLO', served: 'spracovaných', incoming: 'v sieti',
    services: 'Katalóg služieb', servicesHint: 'Vyber dlaždicu a nasaď službu.', select: 'Vyber dlaždicu v clustri',
    tile: 'Dlaždica', level: 'Úroveň', upgrade: 'Vylepšiť', sell: 'Predať', max: 'Maximálna úroveň', deployed: 'Nasadené služby',
    start: 'Spustiť piatok', pause: 'Pauza', resume: 'Pokračovať', speed: 'Rýchlosť hry', sound: 'Zvuk', help: 'Runbook',
    planning: 'Postav prvú líniu obrany.', planningHint: 'Začni s API Podom a Valkey vedľa vysvietenej cesty. Prevádzku platíš až po štarte.',
    cluster: 'eu-central-1 / friday-cluster', clusterHint: 'Klikni na dlaždicu a stavaj · klikni na službu a spravuj ju',
    keyboard: 'Šípky vyberajú dlaždicu · Enter otvorí menu · Escape ho zatvorí',
    abilities: 'ON-CALL VÝBAVA', restart: 'Reštart podu', rollback: 'Rollback', hotfix: 'Hotfix', mute: 'Stíšiť alert',
    restartHint: 'Vybraný alebo zaseknutý API pod: vyčistí zaseknutie, potom 3 s nefunguje. Cooldown 18 s.',
    rollbackHint: 'Obnoví cluster aj rozpočet spred 10 sekúnd. Raz za piatok, aj po incidente.',
    hotfixHint: '2× spracovanie na 10 s, potom 5 s polovičnou rýchlosťou. Cooldown 45 s.',
    muteHint: 'Stíši Slack na 15 s. Produkcia je stále rovnako pokazená. Cooldown 20 s.',
    used: 'použité', readyAbility: 'pripravené', monitoring: 'MONITORING', latency: 'Latencia spracovania', errors: 'Chybovosť', throughput: 'Priepustnosť',
    latencyHint: 'Priemerný čas od príchodu po spracovanie za poslednú sekundu.', errorsHint: 'Úniky a timeouty / všetky dokončené requesty za poslednú sekundu.',
    slack: '#prod-on-fire', online: '1 online', muted: 'Notifikácie stíšené. Problémy zostali.',
    deploy: 'alex · 16:55', deployText: 'mergol som drobný fix. už idem ✌️',
    newsletter: 'Marketing poslal newsletter.', hn: 'Niekto dal link na Hacker News.', migration: 'Beží migrácia DB. Posledný úsek je na 20 s pomalší.',
    welcome: 'Máš 190 €. Možno si prečítaj runbook.', reserved: 'Vstup, DB a smerovacie uzly musia zostať voľné.',
    occupied: 'Na tejto dlaždici je služba alebo request.', funds: 'Nedostatok cloud budgetu.', blocked: 'Nechaj otvorenú cestu od vstupu a oboch uzlov k DB.',
    built: 'Služba nasadená. Čo by sa mohlo pokaziť?', upgraded: 'Vylepšené. Bez jediného meetingu.', sold: 'Služba odstránená. 65 % vrátených.',
    selectPod: 'Vyber API Pod na reštart.', jammed: 'Upload zasekol pod. Vyber ho a reštartuj [1].', rollbackWait: 'Rollback potrebuje 10 sekúnd histórie.',
    restartMessage: 'Skúsili ste to vypnúť a zapnúť?', rollbackMessage: 'Posledných 10 sekúnd sa nikdy nestalo.', hotfixMessage: 'Ship it. Tech debt vyrieši tvoje budúce ja.', muteMessage: 'Všetko je v poriadku. 🔕',
    incident: 'Produkcia opustila chat.', bankrupt: 'Cloud odmietol tvoju kartu.', survived: 'Je polnoc. Môžeš sa odhlásiť.',
    lostCopy: 'Incident report počká. Ďalší pokus začína s rovnakým seedom.',
    wonCopy: 'Sedem vĺn. Jedna vývojárka. Produkcia stále žije. Endless mód je odomknutý.',
    again: 'Skúsiť tento piatok znovu', newSeed: 'Nový piatok', endless: 'Nekonečná smena', endlessLocked: 'Preži piatok a odomkni endless',
    leaderboard: 'Lokálne rekordy smien', noRecords: 'Prvá smena je ešte pred tebou.', seed: 'Seed', close: 'Zavrieť',
    runbookTitle: 'Veľmi neoficiálny runbook',
    rules: [
      'Bráň DB počas siedmich 75-sekundových vĺn (asi 9 minút). Nespracované requesty znižujú SLO. Nulové SLO alebo prázdny rozpočet ukončia smenu.',
      'Klikni na prázdnu dlaždicu a vyber službu. Služby blokujú dlaždice, no hra nedovolí uzavrieť cestu. Kliknutím službu vylepšíš (po úroveň 3) alebo predáš za 65 %.',
      'Začni s API Podom a Valkey pri vysvietenej ceste. Stavať môžeš aj počas vĺn. Za spracovanie dostávaš €; každá služba má prevádzkové náklady. Sleduj ich.',
      'GET je rýchly; POST potrebuje queue. Boti ignorujú cache. Veľké uploady spomaľujú cestu a môžu zaseknúť pody. Retry po 18 s na timeoute vytvorí tri nové requesty, najviac dve generácie.',
      'Load balancer posiela requesty cez dva modré uzly. Po vylepšení uprednostní prázdnejšiu vetvu. Autoscaler pridá dočasnú kapacitu blízkym podom pri piatich requestoch; škálovanie stojí extra.',
      'Klávesy 1–4 aktivujú schopnosti. Reštartuj vybraný alebo zaseknutý pod. Rollback funguje raz, aj po prehre. Medzerník pozastaví hru. Smena sa pozastaví aj po odchode z karty.',
    ],
    hot: 'HOTFIX · 2× spracovanie', debt: 'TECH DEBT · ½ spracovanie', jam: 'ZASEKNUTÝ', offline: 'REŠTART', scaling: 'ŠKÁLUJE',
    unavailable: 'Cluster potrebuje WebGL. Zapni hardvérovú akceleráciu a obnov stránku.', reload: 'Obnoviť hru',
  },
};
export const descriptions = {
  en: {
    pod: ['Processes one request at a time. Uploads can jam it.', '+1 replica / simultaneous target'],
    cache: ['Instant GET hits after learning a color. Bots bypass it.', 'Longer TTL + faster cache lookups'],
    balancer: ['Splits traffic through two routing junctions.', 'Weighted routing to the quieter lane'],
    limiter: ['Slows and drops bots. Keeps the swarm in check.', 'Per-token: slows all traffic + more bot targets'],
    queue: ['Holds POSTs safely and processes them in order.', '+1 consumer +3 buffer slots'],
    autoscaler: ['Adds nearby pod replicas in spikes. +€0.70/s per level while active.', 'Faster scale-up +1 temporary replica'],
  },
  sk: {
    pod: ['Spracúva jeden request naraz. Upload ho môže zaseknúť.', '+1 replika / súčasný cieľ'],
    cache: ['GET po zapamätaní farby zmizne ihneď. Boti ju obídu.', 'Dlhšie TTL + rýchlejšie vyhľadávanie'],
    balancer: ['Rozdeľuje traffic cez dva smerovacie uzly.', 'Váhované smerovanie do voľnejšej vetvy'],
    limiter: ['Spomaľuje a zahadzuje botov. Drží roj na uzde.', 'Per-token: spomalí všetkých + viac cieľov'],
    queue: ['Bezpečne zachytí POSTy a spracúva ich v poradí.', '+1 consumer +3 miesta v buffri'],
    autoscaler: ['V špičke pridá blízkym podom repliky. Pri škálovaní +0,70 €/s za úroveň.', 'Rýchlejší scale-up +1 dočasná replika'],
  },
};
